site_name: Japanese Grammar Guide
theme:
  name: material
  font:
    text: Noto Sans JP
  features:
    - navigation.sections
  palette:
    primary: pink
    accent: green
extra_css:
  # - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - footnotes
  - pymdownx.details
nav:
  - 'index.md'
  - Fundamentals:
    - 'Fundamentals/sentence-structures.md'
    - 'Fundamentals/a-and-b.md'
    - 'Fundamentals/description-inflection.md'
    - 'Fundamentals/particles.md'
    - 'Fundamentals/word-order.md'
    - 'Fundamentals/transitive-intransitive.md'
  - Essential Grammar:
    - 'Essential Grammar/3. Essential Grammar.md'
  - Special Expressions:
    - 'Special Expressions/4. Special Expressions.md'
  - Advanced Grammar:
    - 'Advanced Grammar/5. Advanced Topics.md'