site_name: Japanese Grammar Guide
theme:
  name: material
  font:
    text: Noto Sans JP
  features:
    - navigation.sections
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/torii-gate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  # - stylesheets/extra.css
# repo_url: https://github.com/wizo06/japanese/issues
# repo_name: FEEDBACK
# edit_uri: ""
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
plugins:
  - git-revision-date
  - search
nav:
  - 'index.md'
  - Fundamentals:
    - 'Fundamentals/sentence-structures.md'
    - 'Fundamentals/a-and-b.md'
    - 'Fundamentals/description.md'
    - 'Fundamentals/inflection.md'
    - 'Fundamentals/particles.md'
    - 'Fundamentals/word-order.md'
    # - 'Fundamentals/transitive-intransitive.md'
  # - Essential Grammar:
    # - 'Essential Grammar/3. Essential Grammar.md'
  # - Special Expressions:
    # - 'Special Expressions/4. Special Expressions.md'
  # - Advanced Grammar:
    # - 'Advanced Grammar/5. Advanced Topics.md'