site_name: Japanese Grammar Guide
theme:
  name: material
  # custom_dir: overrides
  font:
    text: Noto Sans JP
    code: Ubuntu Mono
  language: en
  features:
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/torii-gate
  palette:
    # Dark mode
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode
    # - media: "(prefers-color-scheme: light)"
    - scheme: default
      primary: cyan
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/wizo06/japanese/discussions
repo_name: Discussions
edit_uri: ""
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - toc:
      permalink: true
plugins:
  # - git-revision-date
  - search
nav:
  - 'index.md'
  - Language Acquisition: 'language-acquisition.md'
  - Grammar Guide:
    - Fundamentals:
      - 'grammar/fundamentals/sentence-structures.md'
      - 'grammar/fundamentals/a-and-b.md'
      - 'grammar/fundamentals/description.md'
      - 'grammar/fundamentals/inflection.md'
      - 'grammar/fundamentals/particles.md'
      - 'grammar/fundamentals/word-order.md'
      - 'grammar/fundamentals/transitive-intransitive.md'
    - Essential:
      - 'grammar/essential/index.md'
    - Advanced:
      - 'grammar/advanced/5. Advanced Topics.md'
    - Special Expressions:
      - 'grammar/expressions/4. Special Expressions.md'
  - 'reference.md'
  - 'contact.md'